services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:80"

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DB_DSN=postgres://postgres:postgres@db:5432/oauth
        depends_on:
            - db

    db:
        image: 'postgres:14.5'
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: oauth
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
    postgres-data:
